"""
DAX Studio Metadata Parser

Purpose:
    Read query metadata exported by dax_studio_schema_extractor.sql and
    extract the Power BI data-source and lineage information required for
    migration planning.

Inputs:
    - output from dax_studio_schema_extractor

Extracted information:
    - Query name
    - Data-load status
    - Server
    - Database
    - Schema
    - Table or view
    - Native SQL
    - Power Query dependencies
    - Connection information

Outputs:
    - Consolidated source inventory
    - Query-to-source lineage
    - Legacy data-source inventory
    - Input for source-to-target mapping preparation
"""

import re
import pandas as pd

# REGX
RE_SQLDB = re.compile(r'Sql\.Database\s*\(\s*"([^"]+)"\s*,\s*"([^"]+)"', re.I)
RE_SCHITEM = re.compile(r'\[\s*Schema\s*=\s*"([^"]+)"\s*,\s*Item\s*=\s*"([^"]+)"\s*\]', re.I)
RE_NQUERY = re.compile(r'(?is)\[\s*Query\s*=\s*"(.*?)"\s*(?:,|\])')
RE_FROMJOIN = re.compile(r'\b(?:from|join)\s+([A-Za-z0-9_\[\]\.\\]+)', re.I)
RE_AUTOGEN = re.compile(r'^(?:_+)?(?:LocalDateTable_|DateTableTemplate_)', re.I)
RE_FILECONTENTS = re.compile(r'File\.Contents\s*\(\s*"([^"]+)"', re.I)
RE_WEBCONTENTS = re.compile(r'Web\.Contents\s*\(\s*"([^"]+)"', re.I)
RE_SHAREPOINT = re.compile(r'SharePoint\.(?:Files|Contents)\s*\(\s*"([^"]+)"', re.I)
RE_FOLDER = re.compile(r'Folder\.(?:Files|Contents)\s*\(\s*"([^"]+)"', re.I)
RE_ODATA = re.compile(r'OData\.Feed\s*\(\s*"([^"]+)"', re.I)

# Excel navigation pattern like: Source{[Item="Values",Kind="Sheet"]}[Data]
RE_ITEMKIND = re.compile(
    r'\[\s*Item\s*=\s*"([^"]+)"\s*,\s*Kind\s*=\s*"([^"]+)"\s*\]',
    re.I
)

def source_info(q: str):
    """
    Returns (source_type, source_location)
    source_location is typically a file path, URL, SharePoint site, or folder path.
    """
    ql = q.lower()

    # SQL
    if "sql.database" in ql:
        return "SQL", None

    # Excel.Workbook
    if "excel.workbook" in ql:
        m = (
            RE_FILECONTENTS.search(q)
            or RE_WEBCONTENTS.search(q)
            or RE_SHAREPOINT.search(q)
            or RE_FOLDER.search(q)
        )
        return "Excel", (m.group(1) if m else None)

    # Csv.Document
    if "csv.document" in ql:
        m = (
            RE_FILECONTENTS.search(q)
            or RE_WEBCONTENTS.search(q)
            or RE_SHAREPOINT.search(q)
            or RE_FOLDER.search(q)
        )
        return "CSV", (m.group(1) if m else None)

    # JSON
    if "json.document" in ql:
        m = RE_FILECONTENTS.search(q) or RE_WEBCONTENTS.search(q)
        return "JSON", (m.group(1) if m else None)

    # OData
    if "odata.feed" in ql:
        m = RE_ODATA.search(q)
        return "OData", (m.group(1) if m else None)

    # SharePoint
    if "sharepoint.files" in ql or "sharepoint.contents" in ql:
        m = RE_SHAREPOINT.search(q)
        return "SharePoint", (m.group(1) if m else None)

    # Folder
    if "folder.files" in ql or "folder.contents" in ql:
        m = RE_FOLDER.search(q)
        return "Folder", (m.group(1) if m else None)

    # Web
    if "web.contents" in ql:
        m = RE_WEBCONTENTS.search(q)
        return "Web", (m.group(1) if m else None)

    return "Other", None


def is_autogenerated(name: str, q: str) -> bool:
    return (
        bool(RE_AUTOGEN.match(name))
        or (name.lower() == "date" and "CALENDARAUTO" in q.upper())
    )


def extract_native_tables(sql: str):
    """Return list of (schema, table) from FROM/JOIN clauses."""

    sql = re.sub(r'/\*.*?\*/', ' ', sql, flags=re.S)
    sql = re.sub(r'--.*?$', ' ', sql, flags=re.M)

    seen = set()
    results = []

    for m in RE_FROMJOIN.finditer(sql):
        obj = (
            m.group(1)
            .replace("[", "")
            .replace("]", "")
            .replace("\\_", "_")
            .rstrip(";,)")
        )

        if obj.startswith("("):
            continue

        parts = obj.split(".")

        if len(parts) == 1:
            schema, table = None, parts[0]
        elif len(parts) == 2:
            schema, table = parts[0], parts[1]
        else:
            schema, table = parts[-2], parts[-1]

        key = (schema, table)

        if table and key not in seen:
            seen.add(key)
            results.append((schema, table))

    return results


# --- MAIN ---
def extract(input_xlsx: str, output_xlsx: str, sheet=0):

    df = pd.read_excel(
        input_xlsx,
        sheet_name=sheet,
        engine="openpyxl"
    )

    required = {"ObjectType", "Name", "QueryDefinition"}
    missing = required - set(df.columns)

    if missing:
        raise ValueError(
            f"Missing required columns: {', '.join(sorted(missing))}"
        )

    objtyp = df["ObjectType"].fillna("").astype(str)
    name = df["Name"].fillna("").astype(str)
    qdef = df["QueryDefinition"].fillna("").astype(str)

    # Remove auto-generated tables (background)
    keep = ~pd.Series(
        [is_autogenerated(n, q) for n, q in zip(name, qdef)],
        dtype=bool
    )

    objtyp = objtyp[keep].reset_index(drop=True)
    name = name[keep].reset_index(drop=True)
    qdef = qdef[keep].reset_index(drop=True)

    rows = []

    for ot, n, q in zip(objtyp, name, qdef):

        stype, src = source_info(q)

        # Server / DB (SQL only)
        m = RE_SQLDB.search(q)
        server, database = (
            (m.group(1), m.group(2))
            if m else
            (None, None)
        )

        # Non-native schema/table (navigation)
        m = RE_SCHITEM.search(q)
        base_schema, base_table = (
            (m.group(1), m.group(2))
            if m else
            (None, None)
        )

        # Excel.Workbook navigation
        mk = RE_ITEMKIND.search(q)

        if stype == "Excel" and mk:
            base_table = mk.group(1)   # Item
            base_schema = mk.group(2)  # Kind

        # Native query
        nq = RE_NQUERY.search(q)

        if nq:

            sql = (
                nq.group(1)
                .replace("#(lf)", "\n")
                .replace("#(tab)", "\t")
            )

            native_tables = extract_native_tables(sql)

            if native_tables:

                for sch, tbl in native_tables:
                    rows.append([
                        ot,          # ObjectType
                        n,           # Name
                        stype,
                        src,
                        server,
                        database,
                        sch,
                        tbl,
                        True
                    ])

            else:

                rows.append([
                    ot,
                    n,
                    stype,
                    src,
                    server,
                    database,
                    base_schema,
                    base_table,
                    True
                ])

        else:

            rows.append([
                ot,
                n,
                stype,
                src,
                server,
                database,
                base_schema,
                base_table,
                False
            ])

    out = pd.DataFrame(
        rows,
        columns=[
            "ObjectType",
            "Name",
            "Source Type",
            "Source",
            "Server",
            "Database",
            "Schema",
            "Table",
            "Native Query"
        ]
    )

    out.to_excel(
        output_xlsx,
        index=False,
        engine="openpyxl"
    )


if __name__ == "__main__":

    INPUT_FILE  = r""  # Input file path here
    OUTPUT_FILE = r""  # Input file path here

    extract(INPUT_FILE, OUTPUT_FILE)

    print(f"Lineage written to {OUTPUT_FILE}")



